export const proJ = 1; // project
export const sttmp = 1; // synced timestamp
export const wsp = 1; // well spring
export const rQ = 1; // request
export const vnt = 1; // vent (emitter)
export const evtCh = 1; // event channel
export const evtChWSpS = 1; // event channel well-springs
export const evtChRmtWSpS = 1; // event channel (remote) well-springs
export const evtChSoliD = 1; // event channel (remote) solid data
export const evtChRmtSoliD = 1; // event channel (remote) solid data
export const evtChRmtRec = 1; // event channel (remote) record
export const ac = 1; // abstract class or interface
export const red = 1; // reducible
